//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlinkTalk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlinkTalk.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera permission was denied. Enable the camera for BlinkTalk in your device settings, then reopen this page..
        /// </summary>
        public static string Camera_CameraPermissionWasDenied {
            get {
                return ResourceManager.GetString("Camera_CameraPermissionWasDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera ready. Press Train and follow the prompts..
        /// </summary>
        public static string Camera_CameraReady {
            get {
                return ResourceManager.GetString("Camera_CameraReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start the camera: {0}.
        /// </summary>
        public static string Camera_CouldNotStartTheCameraX0Format {
            get {
                return ResourceManager.GetString("Camera_CouldNotStartTheCameraX0Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training successful! I detected your “{0}” gesture. Ensure ‘Use camera’ is ticked so you can use it..
        /// </summary>
        public static string Camera_DetectedX0GestureFormat {
            get {
                return ResourceManager.GetString("Camera_DetectedX0GestureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye gesture.
        /// </summary>
        public static string Camera_EyeGesture {
            get {
                return ResourceManager.GetString("Camera_EyeGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold time: {0:0.0} seconds.
        /// </summary>
        public static string Camera_HoldTimeX0SecondsFormat {
            get {
                return ResourceManager.GetString("Camera_HoldTimeX0SecondsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t detect a clear, repeatable gesture - let&apos;s try again..
        /// </summary>
        public static string Camera_Instructions_CouldNotDetectGesture {
            get {
                return ResourceManager.GetString("Camera_Instructions_CouldNotDetectGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look at the screen and relax your face. Do not look at the camera..
        /// </summary>
        public static string Camera_Instructions_LookAtCamera {
            get {
                return ResourceManager.GetString("Camera_Instructions_LookAtCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now make your indicating gesture and hold it until I tell you to relax. I recommend you look up..
        /// </summary>
        public static string Camera_Instructions_MakeIndicatingGesture {
            get {
                return ResourceManager.GetString("Camera_Instructions_MakeIndicatingGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now relax..
        /// </summary>
        public static string Camera_Instructions_NowRelax {
            get {
                return ResourceManager.GetString("Camera_Instructions_NowRelax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learnt gestured.
        /// </summary>
        public static string Camera_LearntGesture {
            get {
                return ResourceManager.GetString("Camera_LearntGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting camera.
        /// </summary>
        public static string Camera_StartingCamera {
            get {
                return ResourceManager.GetString("Camera_StartingCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold your gesture and the bar fill with time. Set the slider where you&apos;d like it to trigger. You&apos;ll hear a beep when the bar reaches it..
        /// </summary>
        public static string Camera_TestingInstructions {
            get {
                return ResourceManager.GetString("Camera_TestingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string Camera_Train {
            get {
                return ResourceManager.GetString("Camera_Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train first.
        /// </summary>
        public static string Camera_TrainFirst {
            get {
                return ResourceManager.GetString("Camera_TrainFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Camera_Training {
            get {
                return ResourceManager.GetString("Camera_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training failed: {0}.
        /// </summary>
        public static string Camera_TrainingFailedX0Format {
            get {
                return ResourceManager.GetString("Camera_TrainingFailedX0Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use camera.
        /// </summary>
        public static string Camera_UseCamera {
            get {
                return ResourceManager.GetString("Camera_UseCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blink.
        /// </summary>
        public static string Gesture_Blink {
            get {
                return ResourceManager.GetString("Gesture_Blink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to look sideways.
        /// </summary>
        public static string Gesture_LookSideways {
            get {
                return ResourceManager.GetString("Gesture_LookSideways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to look up.
        /// </summary>
        public static string Gesture_LookUp {
            get {
                return ResourceManager.GetString("Gesture_LookUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raise eyebrows.
        /// </summary>
        public static string Gesture_RaiseEyebrows {
            get {
                return ResourceManager.GetString("Gesture_RaiseEyebrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smile.
        /// </summary>
        public static string Gesture_Smile {
            get {
                return ResourceManager.GetString("Gesture_Smile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application tried to access a page that does not exist. Please report this issue..
        /// </summary>
        public static string NotFound_ErrorDescription {
            get {
                return ResourceManager.GetString("NotFound_ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound_NotFound {
            get {
                return ResourceManager.GetString("NotFound_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant presses space-bar on keyboard.
        /// </summary>
        public static string Settings_AssistantPressesSpaceBarOnKeyboard {
            get {
                return ResourceManager.GetString("Settings_AssistantPressesSpaceBarOnKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant taps screen or clicks mouse.
        /// </summary>
        public static string Settings_AssistantTapsScreenOrClicksMouse {
            get {
                return ResourceManager.GetString("Settings_AssistantTapsScreenOrClicksMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator method.
        /// </summary>
        public static string Settings_IndicatorMethod {
            get {
                return ResourceManager.GetString("Settings_IndicatorMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard layout.
        /// </summary>
        public static string Settings_KeyboardLayout {
            get {
                return ResourceManager.GetString("Settings_KeyboardLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alphabetical.
        /// </summary>
        public static string Settings_KeyboardLayout_Alphabetical {
            get {
                return ResourceManager.GetString("Settings_KeyboardLayout_Alphabetical", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Settings_KeyboardLayout_Speed {
            get {
                return ResourceManager.GetString("Settings_KeyboardLayout_Speed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scan speed.
        /// </summary>
        public static string Settings_ScanSpeed {
            get {
                return ResourceManager.GetString("Settings_ScanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This how many seconds to wait before the selection moves on to the next item. Lower is faster..
        /// </summary>
        public static string Settings_ScanSpeed_Description {
            get {
                return ResourceManager.GetString("Settings_ScanSpeed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan speed: {0:0.0} seconds per step.
        /// </summary>
        public static string Settings_ScanSpeed_ScanSpeedX0SecondsPerStepFormat {
            get {
                return ResourceManager.GetString("Settings_ScanSpeed_ScanSpeedX0SecondsPerStepFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading language pack: {0}.
        /// </summary>
        public static string Settings_DownloadingLanguagePackX0Format {
            get {
                return ResourceManager.GetString("Settings_DownloadingLanguagePackX0Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The language pack could not be downloaded. Please check your internet connection and try again..
        /// </summary>
        public static string Settings_LanguagePackDownloadFailed {
            get {
                return ResourceManager.GetString("Settings_LanguagePackDownloadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set up camera.
        /// </summary>
        public static string Settings_SetUpCamera {
            get {
                return ResourceManager.GetString("Settings_SetUpCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use camera to detect eye gesture.
        /// </summary>
        public static string Settings_UseCameraToDetectEyeGesture {
            get {
                return ResourceManager.GetString("Settings_UseCameraToDetectEyeGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Shared_Cancel {
            get {
                return ResourceManager.GetString("Shared_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Shared_Done {
            get {
                return ResourceManager.GetString("Shared_Done", resourceCulture);
            }
        }
    }
}
